// <auto-generated />
namespace Movie_DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixMe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixMe));
        
        string IMigrationMetadata.Id
        {
            get { return "201710191259256_fixMe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
